### ISSUE TITLE
ddcloud_server anomaly - Adding Windows host doesn't render all properties causing host to be deleted on a reapply

### ISSUE THREAD

**Issue by wninobla** [DimensionDataResearch/terraform-provider-ddcloud#20] opened 2016-09-23 02:34 UTC
Hi,

So, I have noticed on a few occasions where building a Windows server is fine.   But, when reapplying a profile to fix a few things that were missed I see the host getting deleted and re-added.  In the plan execution I get the following:

```
-/+ ddcloud_server.util01-server
    admin_password:               "<sensitive>" => "<sensitive>" (attribute changed)
    auto_start:                   "" => "true"
    cpu_count:                    "2" => "2"
    customer_image_id:            "" => "<computed>"
    customer_image_name:          "" => "<computed>"
    disk.#:                       "1" => "1"
    disk.3184022418.disk_id:      "9d572849-9fa9-4ae3-822a-57c361db78e1" => "<computed>"
    disk.3184022418.scsi_unit_id: "0" => "0"
    disk.3184022418.size_gb:      "50" => "50"
    disk.3184022418.speed:        "STANDARD" => "STANDARD"
    dns_primary:                  "" => "8.8.8.8" (forces new resource)
    dns_secondary:                "" => "8.8.4.4" (forces new resource)
    memory_gb:                    "4" => "4"
    name:                         "UTIL01" => "UTIL01"
    networkdomain:                "0e94d76e-9f21-4731-ba83-6473cf66c613" => "0e94d76e-9f21-4731-ba83-6473cf66c613"
    os_image_id:                  "c509d9db-81ce-466b-8ab8-277cee5c964c" => "<computed>"
    os_image_name:                "" => "Win2012 R2 Std 2 CPU" (forces new resource)
    primary_adapter_ipv4:         "192.168.3.11" => "192.168.3.11"
    primary_adapter_ipv6:         "2607:f480:211:1287:1dcd:32d3:eeb3:7175" => "<computed>"
    primary_adapter_vlan:         "de4f6344-b0d5-4469-82ec-8dd53479eb43" => "<computed>"
    public_ipv4:                  "" => "<computed>"
    tag.#:                        "1" => "1"
    tag.3818412570.name:          "Application" => "Application"
    tag.3818412570.value:         "Utility" => "Utility"
```

When I run the terraform state show on that server at the command line I get the following:

```
[root@192-168-104-251 cisco_demo]# terraform state show ddcloud_server.util01-server
id                   = 69199b03-9ddf-433b-9d6a-ee50f31e832a
public_ipv4          =
tag.#                = 1
tag.3818412570.name  = Application
tag.3818412570.value = Utility

```

Running the same command yields the correct results afterwards.  Not sure if this a bug but I wanted to report it anyway.  If my current .tf file is needed just let me know.  Thanks!

**Comment by tintoy** [comment] 2016-09-23 03:19
Hmm, that is odd. Our provider doesn't actually understand the difference between a Windows and a Linux server (it treats them both the same).

Are you able to attach the full configuration you're using? I'll see if I can reproduce the problem.

**Comment by wninobla** [comment] 2016-09-23 03:40
Here it is...  Latest version.  I left the password out so you can use your own. =)

[deploydemo  - code.txt](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/files/488822/deploydemo.-.code.txt)

**Comment by wninobla** [comment] 2016-09-23 03:44
BTW, a new clean run went off without a hitch.  I checked the Windows host and the values were there.  Maybe I'll set the debug on next time but for now I didn't get the error I saw last time.

**Comment by tintoy** [comment] 2016-09-23 09:57
Hmm, this worked for me too.

Since I can't reproduce the problem (and it's not happening to you either) I'm going to close this issue but feel free to reopen it if you disagree or hit the issue again.

Either way, thanks for taking the time to report it :)

**Closed as completed** 2016-09-23 09:59 UTC
Labels: can't reproduce

**Comment by wninobla** [comment] 2016-09-23 10:23
Yeah, I think it's when it fails where the problem gets interesting.  If it comes up again I'll report it.  Thanks!
