### ISSUE TITLE
ports property in ddcloud_port_list resources cause the terraform to crash

### ISSUE THREAD

**Issue by kumarappanc** [DimensionDataResearch/terraform-provider-ddcloud#71] opened 2016-12-06 03:17 UTC
When applying the following resource terraform crashes

```hcl
resource "ddcloud_port_list" "test_port_list1" {
       name = "test_port_list1"
       description = "test_port_list1"
       networkdomain = "${ddcloud_networkdomain.network_domain.id}"
       ports = [80]
}
```

```
Error:
Error applying plan:

1 error(s) occurred:
 interface conversion: interface is string, not int
* ddcloud_port_list.test_port_list1: unexpected EOF
```

When I use the port option instead of ports, it works.

**Comment by tintoy** [comment] 2016-12-06 03:38
Hi.

It's a list of strings not a list of integers (try `"80"` instead of `80`), so technically this behaviour is by design. This is because all other port values (e.g. in firewall rules) in our resources are specified as strings (mainly because in some places, `any` is a valid port).

Having said that, I understand that it could be confusing so I'm open to switching them to purely integers. Is that what you'd prefer? Either way, I'll update the documentation so that it's more explicit in describing the property data type.

**CC**: @mingsheng36 @wninobla

**Comment by tintoy** [comment] 2016-12-06 03:42
Actually, looking at the documentation it already shows examples where they ports are integers. I'm just going to switch it over to being integers. This will be fixed in v1.2 but if you need to keep working for now, just wrap each port in quotes (e.g. `"80"` instead of `80`) and you'll be good to go. Later when you upgrade to v1.2 you can simply remove the quotes and everything will keep working.

**Comment by wninobla** [comment] 2016-12-06 03:45
I don't think we can use a port list here unless we explicitly keep each group of ports explicit.  In the case of doing noncontinuous ports like in the simple example, you'd have to parse it out that way.  May be easy to change on your end but I'm not the one coding.  😀. I am good so long as I know what it expects integer vs. a string.

**Comment by wninobla** [comment] 2016-12-06 03:46
Ok you answered my question on the same note... Lol

**Comment by kumarappanc** [comment] 2016-12-06 03:47
Even the string values doesn't work.

It looks like the problem is in the following function

func (helper resourcePropertyHelper) GetIntSetItems(key string) (items []int) {
	value, ok := helper.data.GetOk(key)
	if !ok || value == nil {
		return
	}
	rawItems := value.(*schema.Set).List()

	items = make([]int, len(rawItems))
	for index, item := range rawItems {
		items[index] = item.(int)
	}

	return
}

conversion item.(int) not working

**Comment by tintoy** [comment] 2016-12-06 03:47
There are actually 2 ways to configure ports in a `ddcloud_port_list`:

1. [Simple](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/blob/development/v1.2/docs/resource_types/port_list.md#simple) (just a list of ports)
2. [Complex](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/blob/development/v1.2/docs/resource_types/port_list.md#complex) (port ranges, etc)

**Comment by tintoy** [comment] 2016-12-06 03:48
@kumarappanc Ugh. Sorry, I'll have to fix that.

Give me 5 mins and I'll see if I can build a hotfixed version of 1.1.x.

**Comment by tintoy** [comment] 2016-12-06 03:57
Ok @kumarappanc - can you give [v1.1.10](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/releases/tag/v1.1.10) a try?

**Comment by tintoy** [comment] 2016-12-06 04:44
BTW, I've updated the [acceptance tests](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/blob/development/v1.2/vendor/ddcloud/resource_port_list_test.go) for `ddcloud_port_list` - they work correctly now.

**Comment by tintoy** [comment] 2016-12-07 06:01
Verified in alpha4.

**Closed as completed by tintoy** 2016-12-07 06:01 UTC
Labels: bug
