### ISSUE TITLE
Support for Disk Speed on Primary Disk ONLY

### ISSUE THREAD

**Issue by mingsheng36** [DimensionDataResearch/terraform-provider-ddcloud#63] opened 2016-11-26 17:34 UTC
Tested deploying with "HIGHPERFORMANCE" disk and also tried to updating the disk speed but is not working. 

Saw from the code under "resource_server_disks.go" line 272 mention that currently there is no support for disk speed. 

Is it possible to add in this feature?

**Comment by tintoy** [comment] 2016-11-26 19:10
If you add a second disk with its speed configured as `HIGHPERFORMANCE` does that work for you?

As far as can I remember, setting the disk speed when creating the disk should work, just not _changing_ the disk speed for an existing disk (this includes the image disk I suspect).

The disk speed stuff is only available in the old v0.9 CloudControl API (XML-only) but I'm sure we can work something out.

- [x] CloudControl API client
  - [x] Expose "change server disk speed" operation
  - [x] Tests
- [x] `ddcloud_server`
  - [x] Support changing of disk speed
  - [x] Tests

**Comment by tintoy** [comment] 2016-11-26 19:11
BTW, thanks for helping to shake out these missing features - keep it coming :)

**Comment by mingsheng36** [comment] 2016-11-27 03:47
_If you add a second disk with its speed configured as HIGHPERFORMANCE does that work for you?_ 
--> ~~Tested and it is not working~~ It is working
_As far as can I remember, setting the disk speed when creating the disk should work, just not changing the disk speed for an existing disk (this includes the image disk I suspect)._
--> ~~Tested and it is not working~~ Not for the primary OS disk, but working for the addtional disks
Server.tf:
```
  disk {
    scsi_unit_id = 0
    size_gb = 21
    speed = "HIGHPERFORMANCE"
  }
  disk {
    scsi_unit_id = 1
    size_gb = 11
    speed = "ECONOMY"
  }
  disk {
    scsi_unit_id = 2
    size_gb = 12
    speed = "HIGHPERFORMANCE"
  }
```
Results:
![image](https://cloud.githubusercontent.com/assets/5947212/20645482/db941066-b49a-11e6-8a04-6acd9f6524d6.png)

**Comment by mingsheng36** [comment] 2016-11-27 04:20
Weird. Right after the above deployment, I tried to run "plan" again (without any changes to server.tf) and seems like there might be some issues with the detecting the size and speed of the first disk (scsi_unit_id: 0) in server.tf and will attempt to update it to 0 GB and speed to "blank".
```
~ ddcloud_server.Test_Server_1
    disk.1830902295.scsi_unit_id: "1" => "1"
    disk.1830902295.size_gb:      "11" => "11"
    disk.1830902295.speed:        "ECONOMY" => "ECONOMY"
    disk.2066820399.scsi_unit_id: "0" => "0"
    disk.2066820399.size_gb:      "21" => "0"
    disk.2066820399.speed:        "STANDARD" => ""
    disk.3105566562.disk_id:      "" => "<computed>"
    disk.3105566562.scsi_unit_id: "" => "0"
    disk.3105566562.size_gb:      "" => "21"
    disk.3105566562.speed:        "" => "HIGHPERFORMANCE"
    disk.3402227464.scsi_unit_id: "2" => "2"
    disk.3402227464.size_gb:      "12" => "12"
    disk.3402227464.speed:        "HIGHPERFORMANCE" => "HIGHPERFORMANCE"
```

**Comment by tintoy** [comment] 2016-11-27 05:41
Hmm. I'll have a poke around while I'm adding the change-disk-speed support and see if anything is amiss.

As for OS disk speed change not taking, that's unsurprising; the problem is that we still have to deploy the machine _and then_ resize the OS disk or change its speed (and the speed change support was what was missing).

**Comment by tintoy** [comment] 2016-11-30 03:45
This can now be tested in [v1.2-preview1](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/releases/tag/v1.2-preview1).

**Comment by mingsheng36** [comment] 2016-11-30 16:20
Okay. Tested and seems like it can only create two disk at most.

```
  # up to 14 disks
  disk {
    scsi_unit_id = 0
    size_gb = 21
    speed = "HIGHPERFORMANCE"
  }
  disk {
    scsi_unit_id = 1
    size_gb = 10
    speed = "ECONOMY"
  }
  disk {
    scsi_unit_id = 2
    size_gb = 10
    speed = "ECONOMY"
  }
```
![image](https://cloud.githubusercontent.com/assets/5947212/20760721/adb7f860-b75b-11e6-8a90-8fdab268942f.png)

ddcloud-terraform-provider --> v1.2-preview1
terraform --> v0.7.13

**Comment by wninobla** [comment] 2016-11-30 16:25
Another one to add to my test script as I didnt test adding multiple disks.  Good catch!


________________________________

**Comment by tintoy** [comment] 2016-11-30 19:26
Can you run with extended logging and attach your log?

**Comment by tintoy** [comment] 2016-11-30 21:43
Ok - have found a couple of bugs (I blame almost 19 hours straight of coding + debugging) and will create a new release once I've tested them.

That's the painful part, of course - it takes around 20 minutes to perform any useful test of server deployment and if the last change hasn't fixed the problem (or shown what the problem is, even) then that's another 25 minutes to try again :(

**Comment by mingsheng36** [comment] 2016-12-01 06:24
Hey @tintoy , really appreciate for those quick fixes, commitment and taking the feedbacks so positively. So  I have tested the disk. Below are the results.

- Deploy disks with different size and speed, OK
- Deploy additional disks with different size and speed, OK
- Update disks size, error
- Update disks speed, error
- Destroy addtional disks, OK

ddcloud-terraform-provider --> v1.2-preview2
terraform --> v0.7.13
[log.txt](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/files/623811/log.txt)

**Comment by tintoy** [comment] 2016-12-01 06:28
Thanks!

Yeah not surprised update doesn’t work yet.

**Comment by tintoy** [comment] 2016-12-01 06:35
Hmm, I can't reproduce that one - could you send me the configuration you're working with?

**Comment by mingsheng36** [comment] 2016-12-01 06:38
```
  # up to 14 disks
  disk {
    //    disk = "<computed>"
    //    disk_id = "<computed>"
    scsi_unit_id = 0
    # only updating of primary disk size is ok, need to set to larger or equal than Client Image's disk size if using it
    size_gb = 21
    # optional - HIGHPERFORMANCE, STANDARD, ECONOMY
    speed = "HIGHPERFORMANCE"
  }
  disk {
    scsi_unit_id = 1
    size_gb = 11
    speed = "ECONOMY"
  }
  disk {
    scsi_unit_id = 2
    size_gb = 12
    speed = "ECONOMY"
  }
  disk {
    scsi_unit_id = 3
    size_gb = 13
    speed = "STANDARD"
  }
  disk {
    scsi_unit_id = 4
    size_gb = 14
    speed = "HIGHPERFORMANCE"
  }
  disk {
    scsi_unit_id = 5
    size_gb = 15
    speed = "ECONOMY"
  }
  disk {
    scsi_unit_id = 6
    size_gb = 16
    speed = "STANDARD"
  }
```

**Comment by tintoy** [comment] 2016-12-01 06:40
Thanks.

And you get the error by running `terraform apply` then running `terraform apply` again?

**Comment by mingsheng36** [comment] 2016-12-01 06:51
Hmm, for the update disk part I can re-create the update part and send u the logs again. I guess the log that I have sent have alot of un-related details.

**Comment by tintoy** [comment] 2016-12-01 07:00
I'm more interested in the steps you took to get there :)

**Comment by mingsheng36** [comment] 2016-12-01 07:16
So the steps are as of below (might not be exactly same as the log because of other tests)
1. Deploy 3 x disks with different size and speed at server deployment
2. Deploy another 3 x additional disks with different size and speed
3. Update one of the disk size
4. Update one of the disk speed
5. Destroy one of the disk

**Comment by tintoy** [comment] 2016-12-01 07:20
Thanks! I'll give that a try. So it sounds like adding disks is OK, but changing them is not? I suspect I may know why but let's see...

**Comment by tintoy** [comment] 2016-12-01 07:29
Ok - yeah, it was because I modelled the disks as a set rather than a list (so Terraform fails to match up the configured disk with its persisted state because changed properties make it look like a different disk).

I'll put up a new build shortly.

**Comment by tintoy** [comment] 2016-12-01 07:44
Ok - give [v1.2-preview3](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/releases/tag/v1.2-preview3) a try :)

**Comment by tintoy** [comment] 2016-12-01 07:44
Note - if you have an existing terraform.tfstate you'll want to destroy any `ddcloud_server` instances before upgrading. Sorry about that.

```
terraform destroy -target=ddcloud_server.my-server
```

**Comment by mingsheng36** [comment] 2016-12-01 07:45
thats the least concern for now :+1:

**Comment by mingsheng36** [comment] 2016-12-01 10:12
Ok, I think we are good to close this. But one last thing, Is it possible to add the below validation?

- Validate to ensure scsi_unit_id "0" is not missing. (CloudControl is able to validate this so it is OK) 
- Validate when updating the "scsi_unit_id" to an already exist "scsi_unit_id" (Currently it removes the disk (force new) that is to be updated first, then it will attempt to re-deploy the disk with the new "scsi_unit_id" but will result in an error from CloudControl due to "scsi_unit_id" is already in use, hence losing the previous disk.

**Comment by tintoy** [comment] 2016-12-01 10:17
That’s worth fixing - I’ll look into it tomorrow.

**Comment by tintoy** [comment] 2016-12-07 06:12
BTW, disk with unit 0 will come from the image so we're good there.

**Comment by tintoy** [comment] 2016-12-07 06:16
Verified in alpha4, and the duplicate-unit-Id check will be in the next release (beta1).

**Comment by tintoy** [comment] 2016-12-07 06:39
[v1.2.0-beta1](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/releases/tag/v1.2.0-beta1)

**Comment by tintoy** [comment] 2016-12-07 06:40
Verified in beta1.

Feel free to reopen (or open a new issue) if you find any (other) problems.

**Closed as completed by tintoy** 2016-12-07 06:40 UTC
Labels: enhancement
