### ISSUE TITLE
Add the ability to enable backups via terraform

### ISSUE THREAD

**Issue by calloes** [DimensionDataResearch/terraform-provider-ddcloud#99] opened 2017-11-27 02:08 UTC
Once server is provisioned and elements such as disk expansion etc are completed we need to add the backup agent.
 
-Need to enable backup initially with specific plan.
-Need to set the file agent storage/schedule/alerting.
-Need to Add Backup Client additionally for Mysql/SQL/Postgre etc.
 
-Need return the backup client download url for the server, this is needed as we will be using ansible to do some client side configs.
 
I assume we would put it inside the ddcloud_server resource
 
Maybe something like.

```
cloudbackup {
    Backup Plan {File and Folder, System State and Applications (Enterprise)}
    Backup Client { 
                    Backup_Client_Type  = Linux File Agent
                    Storage_Policy      = 14 Day Storage + Secondary Copy
                    Schedule Policy      = 1am – 3am
                    Alerting            = all 
                    Email              = me@me.com
    }
    Backup Client {
                    Backup_Client_Type  = MySql Agent
                    Storage_Policy      = 14 Day Storage + Secondary Copy
                    Schedule Policy      = 1am – 3am
                    Alerting            = all 
                    Email              = me@me.com
    }
}
```

**Comment by tintoy** [comment] 2017-11-27 02:46
Cool, and I assume that these values can be changed after the server has been deployed?

**Comment by calloes** [comment] 2017-11-28 05:03
Yes can only be activated after server deployment is completed

**Comment by tintoy** [comment] 2018-01-04 04:47
Closing as a duplicate of #26 (we'll track this issue there).

**Closed as completed by tintoy** 2018-01-04 04:47 UTC
