### ISSUE TITLE
What to do on "Incompatible API version with plugin" error message?

### ISSUE THREAD

**Issue by bernard357** [DimensionDataResearch/terraform-provider-ddcloud#95] opened 2017-10-06 05:43 UTC
Hello there. This are the messages returned by terraform:

```
$ terraform validate
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * provider.ddcloud: Incompatible API version with plugin. Plugin version: 1, Ours: 4
```

Can you help please?

**Comment by tintoy** [comment] 2017-10-06 06:05
What version of Terraform are you using?

Run `terraform version` to check.

**Comment by tintoy** [comment] 2017-10-06 06:20
Usually this message means the version of the `ddcloud` provider you are using was built against an older or newer version of Terraform. If you're on v1.3.x of the `ddcloud` provider, you need Terraform v0.8.1 or newer; if you're on v1.2.x or older, you need Terraform v0.7.x or older.

**Comment by bernard357** [comment] 2017-10-06 08:05
```
$ terraform --version
Terraform v0.10.7
```

The version of the dd cloud provider is the most recent release from the GitHub site.

**Comment by tintoy** [comment] 2017-10-06 08:12
v1.3.0 supports Terraform v0.9.x - I think v0.10.x is not supported yet. Make sure you're on v1.3.0 of the provider and v0.9.x of Terraform. Our next release (v1.4.x) will support Terraform v0.10.x.

**Comment by tintoy** [comment] 2017-10-06 08:14
Sorry about that. Part of the problem is they keep changing the plugin protocol and its not backward-compatible. So each version of our provider can only target a specific version of Terraform (more or less).

**Comment by tintoy** [comment] 2017-10-12 21:12
Hey @bernard357 - did that fix it for you?

**Comment by bernard357** [comment] 2017-10-13 00:23
Hello Adam, I am on vacation for a family trip this week, and Will look at
it by next week. Thanks for the follow up :-)

-Bernard

**Comment by tintoy** [comment] 2017-12-11 00:17
@bernard357 hi, sorry it's taken me a while to circle back to this (I kinda forgot about it). Are you still having problems?

**Comment by bernard357** [comment] 2017-12-28 17:52
Hello Adam, thanks for asking. I had no time to come back to this, sorry.

Take care

Bernard

**Comment by tintoy** [comment] 2018-01-04 04:44
No problem - I'm going to close this issue for now, but please feel free to reopen it if you find the problem has not been resolved :)

**Closed as completed by tintoy** 2018-01-04 04:44 UTC
